services:
  mood-db:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"
    restart: always

  mood-api-dev:
    build:
      context: services/backend/mood
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - DB_USER=user
      - DB_PASSWORD=pass
      - DB_HOST=mood-db
      - DB_PORT=5432
    develop:
      watch:
        - action: sync
          path: services/backend/mood
          target: /app
        - action: rebuild
          path: services/backend/mood/build.mill
          
  frontend-dev:
    build:
      context: services/frontend/demdemfront
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    develop:
      watch:
        - action: sync
          path: services/frontend/demdemfront
          target: /app